--- 
jobs: 
  build-js: 
    name: "Build Js/Css"
    runs-on: ubuntu-latest
    steps: 
      - 
        uses: actions/checkout@v1
      - 
        name: "Yarn Build"
        run: |
            yarn install
            yarn prod
            cat public/mix-manifest.json # See asset versions in log
      - 
        name: "Upload build files"
        uses: actions/upload-artifact@v1
        with: 
          name: assets
          path: public
  deploy: 
    if: "github.ref == 'refs/heads/main'"
    name: "Deploy to Production"
    needs: 
      - build-js
      - test-php
    runs-on: ubuntu-latest
    steps: 
      - 
        uses: actions/checkout@v1
      - 
        name: "Download build assets"
        uses: actions/download-artifact@v1
        with: 
          name: assets
          path: public
      - 
        name: "Setup PHP"
        uses: shivammathur/setup-php@master
        with: 
          extension-csv: "mbstring, bcmath"
          php-version: "7.4.3"
      - 
        name: "Composer install"
        run: "composer install"
      - 
        name: "Setup Deployer"
        uses: atymic/deployer-php-action@master
        with: 
          ssh-known-hosts: "${{ secrets.SSH_KNOWN_HOSTS }}"
          ssh-private-key: "${{ secrets.SSH_PRIVATE_KEY }}"
      - 
        env: 
          DOT_ENV: "${{ secrets.DOT_ENV }}"
        name: "Deploy to Prod"
        run: "dep deploy production --tag=${{ env.GITHUB_REF }} -vvv"
  test-php: 
    name: "Test/Lint PHP"
    needs: build-js
    runs-on: ubuntu-latest
    steps: 
      - 
        uses: actions/checkout@v1
      - 
        name: "Setup PHP"
        uses: shivammathur/setup-php@master
        with: 
          extension-csv: "mbstring, bcmath"
          php-version: "7.4.3"
      - 
        name: "Composer install"
        run: "composer install"
name: CI-CD
true: 
  push: 
    branches: main

